/******************************************************************************\
*																			  *
*	Copyright © 2009-2010 Theo Brinkman. All rights reserved.					   *
*																			  *
*	This work is licensed under a Creative Commons							 *
*	Attribution-Noncommercial-No Derivative Works 3.0 United States License.   *
*																			  *
*	See COPYING.TXT for details.											   *
*																			  *
\******************************************************************************/
#pragma once

namespace Input
{
	enum KeyCodes: unsigned short
	{
		KEY_FIRST = 0,
		KEY_0,
		KEY_1,
		KEY_2,
		KEY_3,
		KEY_4,
		KEY_5,
		KEY_6,
		KEY_7,
		KEY_8,
		KEY_9,
		KEY_A,
		KEY_ABNT_C1,
		KEY_ABNT_C2,
		KEY_ADD,
		KEY_AMPERSAND,
		KEY_APOSTROPHE,
		KEY_APPS,
		KEY_ASTERISK,
		KEY_AT,
		KEY_AX,
		KEY_B,
		KEY_BACK,
		KEY_BACKQUOTE,
		KEY_BACKSLASH,
		KEY_BREAK,
		KEY_C,
		KEY_CALCULATOR,
		KEY_CAPITAL,
		KEY_CARET,
		KEY_CLEAR,
		KEY_COLON,
		KEY_COMMA,
		KEY_COMPOSE,
		KEY_CONVERT,
		KEY_D,
		KEY_DECIMAL,
		KEY_DELETE,
		KEY_DIVIDE,
		KEY_DOLLAR,
		KEY_DOWN,
		KEY_E,
		KEY_END,
		KEY_EQUALS,
		KEY_ESCAPE,
		KEY_EURO,
		KEY_EXCLAIM,
		KEY_F,
		KEY_F1,
		KEY_F2,
		KEY_F3,
		KEY_F4,
		KEY_F5,
		KEY_F6,
		KEY_F7,
		KEY_F8,
		KEY_F9,
		KEY_F10,
		KEY_F11,
		KEY_F12,
		KEY_F13,
		KEY_F14,
		KEY_F15,
		KEY_G,
		KEY_GRAVE,
		KEY_GREATER,
		KEY_H,
		KEY_HASH,
		KEY_HELP,
		KEY_HOME,
		KEY_I,
		KEY_INSERT,
		KEY_J,
		KEY_K,
		KEY_KANA,
		KEY_KANJI,
		KEY_L,
		KEY_LALT,
		KEY_LBRACKET,
		KEY_LCONTROL,
		KEY_LEFT,
		KEY_LESS,
		KEY_LPAREN,
		KEY_LMENU,
		KEY_LMETA,
		KEY_LSHIFT,
		KEY_LSUPER,
		KEY_LWIN,
		KEY_M,
		KEY_MAIL,
		KEY_MEDIASELECT,
		KEY_MEDIASTOP,
		KEY_MENU,
		KEY_MINUS,
		KEY_MODE,
		KEY_MULTIPLY,
		KEY_MUTE,
		KEY_MYCOMPUTER,
		KEY_N,
		KEY_NEXT,
		KEY_NEXTTRACK,
		KEY_NOCONVERT,
		KEY_NUMLOCK,
		KEY_NUMPAD0,
		KEY_NUMPAD1,
		KEY_NUMPAD2,
		KEY_NUMPAD3,
		KEY_NUMPAD4,
		KEY_NUMPAD5,
		KEY_NUMPAD6,
		KEY_NUMPAD7,
		KEY_NUMPAD8,
		KEY_NUMPAD9,
		KEY_NUMPAD_COMMA,
		KEY_NUMPAD_DIVIDE,
		KEY_NUMPAD_ENTER,
		KEY_NUMPAD_EQUALS,
		KEY_NUMPAD_MINUS,
		KEY_NUMPAD_MULTIPLY,
		KEY_NUMPAD_PERIOD,
		KEY_NUMPAD_PLUS,
		KEY_O,
		KEY_OEM_102,
		KEY_P,
		KEY_PAGEUP,
		KEY_PAGEDOWN,
		KEY_PAUSE,
		KEY_PERIOD,
		KEY_PLAYPAUSE,
		KEY_POWER,
		KEY_PREVTRACK,
		KEY_PRIOR,
		KEY_PRINT,
		KEY_Q,
		KEY_QUESTION,
		KEY_QUOTE,
		KEY_R,
		KEY_RALT,
		KEY_RBRACKET,
		KEY_RCONTROL,
		KEY_RETURN,
		KEY_RIGHT,
		KEY_RMENU,
		KEY_RMETA,
		KEY_RPAREN,
		KEY_RSHIFT,
		KEY_RSUPER,
		KEY_RWIN,
		KEY_S,
		KEY_SCROLL,
		KEY_SEMICOLON,
		KEY_SLASH,
		KEY_SLEEP,
		KEY_SPACE,
		KEY_STOP,
		KEY_SUBTRACT,
		KEY_SYSRQ,
		KEY_T,
		KEY_TAB,
		KEY_U,
		KEY_UNDERLINE,
		KEY_UNDO,
		KEY_UNLABELED,
		KEY_UP,
		KEY_V,
		KEY_VOLUMEDOWN,
		KEY_VOLUMEUP,
		KEY_W,
		KEY_WAKE,
		KEY_WEBBACK,
		KEY_WEBFAVORITES,
		KEY_WEBFORWARD,
		KEY_WEBHOME,
		KEY_WEBREFRESH,
		KEY_WEBSEARCH,
		KEY_WEBSTOP,
		KEY_X,
		KEY_Y,
		KEY_YEN,
		KEY_Z,
		//INSERT ANY OTHER KEYS ABOVE THIS LINE!
		KEY_LAST = 255,
		KEY_UNKNOWN = 0
	};
}

class IInputManager
{
#pragma message("-- IInputManager is included")
public:
	virtual void PollInputs() = 0;

	virtual bool KeyDown(Input::KeyCodes key) = 0;
	virtual bool KeyWasDown(Input::KeyCodes key) = 0;
	virtual bool KeyPress(Input::KeyCodes key) = 0;
	virtual bool KeyHeld(Input::KeyCodes key) = 0;

	virtual long MouseX() = 0;
	virtual long MouseY() = 0;
	virtual bool MouseButtonDown(int button) = 0;

	virtual void Release() = 0;

	virtual ~IInputManager(){};
};